# Generated by Django 5.0.6 on 2024-05-12 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fec_public', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=30)),
                ('localizacion', models.CharField(max_length=255)),
                ('fec_evento', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fec_public', models.DateTimeField(auto_now_add=True)),
                ('subtitulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fec_public', models.DateTimeField(auto_now_add=True)),
                ('nom_mascota', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('1', 'Macho'), ('2', 'Hembra')], max_length=20)),
                ('tamaño', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fec_public', models.DateTimeField(auto_now_add=True)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
